# Site settings
title: Logobridge
email: 
description: > # this means to ignore newlines until "baseurl:"
  Logobridge is a collection of unused logo proposals in the Public Domain, so you are free to use them as a placeholder for your project or as a template for your upcoming logo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://logobridge.co" # the base hostname & protocol for your site
twitter_username: uracreative
github_username: uracreative

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]