# Site settings
title: Logobridge
email: logobridge@ura.design
description: > # this means to ignore newlines until "baseurl:"
  Logobridge is a collection of public domain logos which can be used by anyone without any restrictions. Need a custom logo with exclusive rights? Name a price and we will create one tailored for you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://logobridge.co" # the base hostname & protocol for your site
twitter_username: logobridge
github_username: uracreative

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
